/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsBooksRouteImport } from './routes/events-books'
import { Route as ContributesRouteImport } from './routes/contributes'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardMyBooksRouteImport } from './routes/dashboard/my-books'
import { Route as DashboardManageBooksRouteImport } from './routes/dashboard/manage-books'
import { Route as BooksBookIdRouteImport } from './routes/books/$bookId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsBooksRoute = EventsBooksRouteImport.update({
  id: '/events-books',
  path: '/events-books',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributesRoute = ContributesRouteImport.update({
  id: '/contributes',
  path: '/contributes',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMyBooksRoute = DashboardMyBooksRouteImport.update({
  id: '/my-books',
  path: '/my-books',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardManageBooksRoute = DashboardManageBooksRouteImport.update({
  id: '/manage-books',
  path: '/manage-books',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/community': typeof CommunityRoute
  '/contributes': typeof ContributesRoute
  '/events-books': typeof EventsBooksRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/dashboard/manage-books': typeof DashboardManageBooksRoute
  '/dashboard/my-books': typeof DashboardMyBooksRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/books/': typeof BooksIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/contributes': typeof ContributesRoute
  '/events-books': typeof EventsBooksRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/dashboard/manage-books': typeof DashboardManageBooksRoute
  '/dashboard/my-books': typeof DashboardMyBooksRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/books': typeof BooksIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/community': typeof CommunityRoute
  '/contributes': typeof ContributesRoute
  '/events-books': typeof EventsBooksRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/dashboard/manage-books': typeof DashboardManageBooksRoute
  '/dashboard/my-books': typeof DashboardMyBooksRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/books/': typeof BooksIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/community'
    | '/contributes'
    | '/events-books'
    | '/login'
    | '/signup'
    | '/books/$bookId'
    | '/dashboard/manage-books'
    | '/dashboard/my-books'
    | '/dashboard/profile'
    | '/books/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/contributes'
    | '/events-books'
    | '/login'
    | '/signup'
    | '/books/$bookId'
    | '/dashboard/manage-books'
    | '/dashboard/my-books'
    | '/dashboard/profile'
    | '/books'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/community'
    | '/contributes'
    | '/events-books'
    | '/login'
    | '/signup'
    | '/books/$bookId'
    | '/dashboard/manage-books'
    | '/dashboard/my-books'
    | '/dashboard/profile'
    | '/books/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  ContributesRoute: typeof ContributesRoute
  EventsBooksRoute: typeof EventsBooksRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events-books': {
      id: '/events-books'
      path: '/events-books'
      fullPath: '/events-books'
      preLoaderRoute: typeof EventsBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributes': {
      id: '/contributes'
      path: '/contributes'
      fullPath: '/contributes'
      preLoaderRoute: typeof ContributesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/my-books': {
      id: '/dashboard/my-books'
      path: '/my-books'
      fullPath: '/dashboard/my-books'
      preLoaderRoute: typeof DashboardMyBooksRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/manage-books': {
      id: '/dashboard/manage-books'
      path: '/manage-books'
      fullPath: '/dashboard/manage-books'
      preLoaderRoute: typeof DashboardManageBooksRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardManageBooksRoute: typeof DashboardManageBooksRoute
  DashboardMyBooksRoute: typeof DashboardMyBooksRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardManageBooksRoute: DashboardManageBooksRoute,
  DashboardMyBooksRoute: DashboardMyBooksRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  CommunityRoute: CommunityRoute,
  ContributesRoute: ContributesRoute,
  EventsBooksRoute: EventsBooksRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  BooksIndexRoute: BooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
