/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FindALibraryRouteImport } from './routes/find-a-library'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardMyBooksRouteImport } from './routes/dashboard/my-books'
import { Route as DashboardManageBooksRouteImport } from './routes/dashboard/manage-books'
import { Route as BooksBookIdRouteImport } from './routes/books/$bookId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FindALibraryRoute = FindALibraryRouteImport.update({
  id: '/find-a-library',
  path: '/find-a-library',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMyBooksRoute = DashboardMyBooksRouteImport.update({
  id: '/my-books',
  path: '/my-books',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardManageBooksRoute = DashboardManageBooksRouteImport.update({
  id: '/manage-books',
  path: '/manage-books',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/agenda': typeof AgendaRoute
  '/discover': typeof DiscoverRoute
  '/find-a-library': typeof FindALibraryRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/signup': typeof SignupRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/dashboard/manage-books': typeof DashboardManageBooksRoute
  '/dashboard/my-books': typeof DashboardMyBooksRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/books/': typeof BooksIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/agenda': typeof AgendaRoute
  '/discover': typeof DiscoverRoute
  '/find-a-library': typeof FindALibraryRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/signup': typeof SignupRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/dashboard/manage-books': typeof DashboardManageBooksRoute
  '/dashboard/my-books': typeof DashboardMyBooksRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/books': typeof BooksIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/agenda': typeof AgendaRoute
  '/discover': typeof DiscoverRoute
  '/find-a-library': typeof FindALibraryRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/signup': typeof SignupRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/dashboard/manage-books': typeof DashboardManageBooksRoute
  '/dashboard/my-books': typeof DashboardMyBooksRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/books/': typeof BooksIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about-us'
    | '/agenda'
    | '/discover'
    | '/find-a-library'
    | '/login'
    | '/news'
    | '/signup'
    | '/books/$bookId'
    | '/dashboard/manage-books'
    | '/dashboard/my-books'
    | '/dashboard/profile'
    | '/books/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/agenda'
    | '/discover'
    | '/find-a-library'
    | '/login'
    | '/news'
    | '/signup'
    | '/books/$bookId'
    | '/dashboard/manage-books'
    | '/dashboard/my-books'
    | '/dashboard/profile'
    | '/books'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/about-us'
    | '/agenda'
    | '/discover'
    | '/find-a-library'
    | '/login'
    | '/news'
    | '/signup'
    | '/books/$bookId'
    | '/dashboard/manage-books'
    | '/dashboard/my-books'
    | '/dashboard/profile'
    | '/books/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutUsRoute: typeof AboutUsRoute
  AgendaRoute: typeof AgendaRoute
  DiscoverRoute: typeof DiscoverRoute
  FindALibraryRoute: typeof FindALibraryRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRoute
  SignupRoute: typeof SignupRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-a-library': {
      id: '/find-a-library'
      path: '/find-a-library'
      fullPath: '/find-a-library'
      preLoaderRoute: typeof FindALibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/my-books': {
      id: '/dashboard/my-books'
      path: '/my-books'
      fullPath: '/dashboard/my-books'
      preLoaderRoute: typeof DashboardMyBooksRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/manage-books': {
      id: '/dashboard/manage-books'
      path: '/manage-books'
      fullPath: '/dashboard/manage-books'
      preLoaderRoute: typeof DashboardManageBooksRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardManageBooksRoute: typeof DashboardManageBooksRoute
  DashboardMyBooksRoute: typeof DashboardMyBooksRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardManageBooksRoute: DashboardManageBooksRoute,
  DashboardMyBooksRoute: DashboardMyBooksRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutUsRoute: AboutUsRoute,
  AgendaRoute: AgendaRoute,
  DiscoverRoute: DiscoverRoute,
  FindALibraryRoute: FindALibraryRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRoute,
  SignupRoute: SignupRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  BooksIndexRoute: BooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
